# Generated by Django 5.2.1 on 2025-05-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='data_reserva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
